GET http://localhost:4000/ping

###
GET http://localhost:4000/eventos

###
GET http://localhost:4000/eventos/evento-python-2025

###
GET http://localhost:4000/eventos/f4b18eb7-13c6-4bde-aa26-a9551a5c31f2

###
GET http://localhost:4000/eventos/validar/evento-fullstack/f4b18eb7-13c6-4bde-aa26-a9551a5c31f2
###
GET http://localhost:4000/eventos/validar/evento-fullstack/21ff36d7-8fa7-495e-9339-d1687458b660

###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

{
  "id": "65965e1c-8055-4795-b4a3-da93bbe97e31",
  "senha": "familia2024!!"
}

###
POST http://localhost:4000/eventos/reuniao-familia-oliveira/convidado
Content-Type: application/json

{
   "id": "f7f5279c-e271-49e8-b1b2-b2d413f3048e",
    "nome": "Ana Julia Maria",
    "email": "anamaria@email.email",
    "confirmado": true,
    "possuiAcompanhantes": true,
    "qtdeAcompanhantes": 10
}

###
POST http://localhost:4000/eventos
Content-Type: application/json

{
    "alias": "evento-python-2025",
    "nome": "Jose Carlos",
    "data": "2024-12-15T10:00:00",
    "local": "Porto Alegre",
    "descricao": "Evento de tecnologia",
    "senha": "familia2025",
    "imagem": "https://www.formacao.dev/assets/img/formacao-dev.png",
    "imagemBackground": "https://www.formacao.dev/assets/img/formacao-dev-background.png",
    "publicoEsperado": 1000,
    "convidados": [
        {
            "nome": "Mariana Santos Sampaio",
            "email": "marianagui@email.email",
            "confirmado": true,
            "possuiAcompanhantes": true,
            "qtdeAcompanhantes": 10
        }
    ]
}
